apiVersion: v1
kind: Service
metadata:
  name: microservice-encounter-condition-service
spec:
  selector:
    app: microservice-encounter-condition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
