apiVersion: v1
kind: Service
metadata:
  name: encounter-condition-db-service
  labels:
    app: encounter-condition-db
spec:
  selector:
    app: encounter-condition-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
