apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-db-deployment
  labels:
    app: message-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-db
  template:
    metadata:
      labels:
        app: message-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Aprilapril23."
            - name: MYSQL_DATABASE
              value: "MessageService"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "Aprilapril23."
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: message-db-pvc
