apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-user
  labels:
    app: microservice-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-user
  template:
    metadata:
      labels:
        app: microservice-user
    spec:
      containers:
        - name: microservice-user
          image: microservice-user:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
